name: Create Release

on:
  # Triggers a release draft whenever we push a version tag (e.g. v1.0.0)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  build-targets-json: '.github/available-build-targets.json'
  build-type: 'RelWithDebInfo'           # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: 'Prepare jobs'
    outputs:
      linux_builds: ${{ steps.parse.outputs.linux_builds }}
      macos_builds: ${{ steps.parse.outputs.macos_builds }}
      windows_builds: ${{ steps.parse.outputs.windows_builds }}
      build_type: ${{ env.build-type }}
      release_name: ${{ steps.parse.outputs.release-name }}
      tag: ${{ steps.parse.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
        with:  # Get the build targets
          sparse-checkout: '${{ env.build-targets-json }}'
          sparse-checkout-cone-mode: false
      - name: 'Parse targets list and setup version string'
        id: parse
        uses: actions/github-script@v8
        with:
          script: |
            const available_targets = require('${{ env.build-targets-json }}')

            core.setOutput('linux_builds', Object.values(available_targets.linux_targets))
            core.setOutput('macos_builds', Object.values(available_targets.macos_targets))
            core.setOutput('windows_builds', Object.values(available_targets.windows_targets))

            const tag = "${{ github.ref_name }}"
            core.setOutput('tag', tag)
            const release_name = "freenote " + tag.substring(1)  // Remove the v
            core.setOutput('release-name', release_name)
            console.log("Building artifacts for release of " + release_name)

  run-ci:
    name: Create installers
    needs: prepare
    permissions:
      contents: read
    uses: ./.github/workflows/create-installers.yml
    with:
      linux_builds: ${{ needs.prepare.outputs.linux_builds }}
      macos_builds: ${{ needs.prepare.outputs.macos_builds }}
      windows_builds: ${{ needs.prepare.outputs.windows_builds }}
      build_type: ${{ needs.prepare.outputs.build_type }}

  publish-result:
    name: Publish
    needs: [run-ci, prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          merge-multiple: true
          path: ${{ github.workspace }}/artifacts
      - name: 'Zipping folder artifacts'
        run: |
          for D in *; do [ -d "${D}" ] && zip -r "${D}.zip" "${D}" > /dev/null && rm -rf "${D}" && echo "Zipped ${D}"; done
          ls -lh
        working-directory: ${{ github.workspace }}/artifacts
      - name: Pull changelog
        uses: actions/checkout@v6
        with:  # Get the changelog
          sparse-checkout: 'debian/changelog'
          sparse-checkout-cone-mode: false
          path: ${{ github.workspace }}/changelog
      - name: 'Prepare release body'
        run: |
          {
            echo 'body<<EOF'
            echo "This is a release of freenote, a Xournal++ fork with Google Ink Stroke Modeler handwriting prediction, 1 Euro stabilization, infinite canvas and multi-image insertion."
            sed -n '/^freenote ([0-9.-]*).*/,/^ -- .*/{ /^freenote .*/! { /^ -- .*/ q;p } }' changelog/debian/changelog
            echo "See https://github.com/readme666/freenote/blob/${{ needs.prepare.outputs.tag }}/CHANGELOG.md for a more detailed list of changes."
            echo EOF
          } >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/artifacts/*"
          draft: true
          allowUpdates: true
          omitDraftDuringUpdate: true
          name: ${{ needs.prepare.outputs.release_name }}
          body: ${{ env.body }}
          removeArtifacts: true
          replacesArtifacts: true
          updateOnlyUnreleased: true
          artifactErrorsFailBuild: true
          tag: ${{ needs.prepare.outputs.tag }}
